title: Ethereal ENgine Helm Chart Repo
description: A chart repo for storing charts.
theme: minima
url: "https://helm.etherealengine.org"
repo_name: etherealengine

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore